# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_secrets', '0002_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='dojo_secrets.Secret')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='dojo_secrets.User')),
            ],
        ),
    ]
